Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

AllCops:
  NewCops: enable

  Exclude:
    - 'generated/**/*.rb'
    - 'bin/bundle'
    - 'config/**/*.rb'
    - 'db/schema.rb'
